### ISSUE TITLE
version check is too strict for custom projects

### ISSUE THREAD

**Issue by YunSuk-Yeo** [cosmos/ledger-cosmos-go#11]
The projects, who are using cosmos-sdk, has no option for the their ledger app versioning.
For the terra, it should make its own ledger application because BIP32 CoinType is different. But below Version checking mechanism force us to use specific version in our custom ledger app

https://github.com/cosmos/ledger-cosmos-go/blob/c03f491cbf1740e5ec7919683019c2c84d9fbc10/user_app.go#L76

**Comment by jleni** [comment]
Hi @YunSuk-Yeo . Thanks for the feedback!
I would be happy to review an alternative. Would you be able to send a PR with a proposal?

The most important aspects you should consider are:
- We use semantic versioning
- We have submitted a new Cosmos app v2 and the API is not backwards compatible so the library needs behave differently for v1 and v2.

**Comment by YunSuk-Yeo** [comment]
@jleni please check the [PR](#12 )
