### ISSUE TITLE
Tag new release or use upstream in sdk

### ISSUE THREAD

**Issue by faddat** [cosmos/ledger-cosmos-go#28]
Only the `master` branch here is up to date with zondax/ledger-cosmos-go

If we would like to continue to maintain this fork, then we should tag a new release.

**Comment by jleni** [comment]
Thanks @faddat, we will be moving everything to this repo (cosmos/ledger-cosmos/go) in the following days.

The process is described here: 
https://github.com/cosmos/ledger-cosmos-go/issues/30

**Comment by ftheirs** [comment]
Done here: https://github.com/cosmos/ledger-cosmos-go/issues/30
