### ISSUE TITLE
depends on zondax/ledger-go

### ISSUE THREAD

**Issue by faddat** [cosmos/ledger-cosmos-go#29]
this repository depends on zondax/ledger-go but we maintain a fork of ledger-go in the cosmos org.  

Reckon that if we want to keep maintaining these forks, we should merge:

* https://github.com/cosmos/ledger-go/pull/6

and use cosmos/ledger-go as the canonical import here to ensure that we don't end up with import spaghetti.

**Comment by ftheirs** [comment]
Done here: https://github.com/cosmos/ledger-cosmos-go/issues/30
