### ISSUE TITLE
Refactor/rework release process

### ISSUE THREAD

**Issue by jleni** [cosmos/ledger-cosmos-go#30]
This issue is related to https://github.com/cosmos/gaia/pull/1801

- [x] align with any changes done in cosmos/ledger-go, move them to zondax/ledger-go
- [x] deprecate cosmos/ledger-go
- [x] release a new version of zondax/ledger-go
- [x] update ledger-cosmos-go to point to zondax/ledger-go
- [x] release ledger-cosmos-go
- [ ] rework fork relations so cosmos/ledger-cosmos-go is the main repo

**Comment by ftheirs** [comment]
All the task related to development were done! I created this task to track the fork relations since it's more related to github repo configuration more than adding some new feature: https://github.com/cosmos/ledger-cosmos-go/issues/38
