### ISSUE TITLE
LedgerCosmos.getAddressPubKeySECP256K1 sends back wrong HRP length recommendation to user

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ledger-cosmos-go#53]
Please take a look at this length check https://github.com/cosmos/ledger-cosmos-go/blob/e9d4c190688a4631fa1157fe8eed99fa86187a4e/user_app.go#L294-L295

It clearly guards that length of the HRP should be less than 83, but the error message says `hrp len should be <10`

/cc @elias-orijtech @julienrbrt

**Comment by jleni** [comment]
The error message is incorrect.

HRP must be between 1 and 83 bytes

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32

This is also the limit in ledger apps.

https://github.com/cosmos/ledger-cosmos/blob/30910a6c0995e2d82ef1041c629440263799cafd/app/src/crypto.h#L29

The error message needs to be updated

**Comment by jleni** [comment]
fix in dev. it will be released soon
