### ISSUE TITLE
LedgerCosmos.getAddressPubKeySECP256K1 could use string operations as they are for properly checking runes instead of bytes

### ISSUE THREAD

**Issue by odeke-em** [cosmos/ledger-cosmos-go#54]
This code takes a string and then converts it to a byteslice then manually runs some operations on it https://github.com/cosmos/ledger-cosmos-go/blob/e9d4c190688a4631fa1157fe8eed99fa86187a4e/user_app.go#L298-L303

and then https://github.com/cosmos/ledger-cosmos-go/blob/e9d4c190688a4631fa1157fe8eed99fa86187a4e/user_app.go#L317-L318

From reading the above, it seems that Ledger ONLY deals with ASCII but I've seen them display emoji so seems that they are capable of using Unicode for future purposes like Unicode passphrases or keys, in which I could use runes (Unicode code point with a very high range) that are invalid but when turned into bytes (very narrow range) overflow and pass the error checks

### Use string operations

```go

func validHRPRune(r rune) bool {
	// https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
	return r >= 33 && r <= 126
}

func (ledger *LedgerCosmos) getAddressPubKeySECP256K1(bip32Path []uint32, hrp string... {
   ...
   if strings.ContainsFunc(hrp, func(r rune) bool { return !validHRPRune(r) }) {
      return nil, "", errors.New("all runes in the HRP must be in the [33, 126] range")
   }

  ...
  message := append(header, byte(len(hrp)))
  message = append(message, hrp...)
```

### Use bytes.ContainsFunc
```go
   if bytes.ContainsFunc(hrpBytes, invalidHRPByte) {
      return nil, "", errors.New("all runes in the HRP must be in the [33, 126] range")
   }
```

/cc @elias-orijtech @julienrbrt

**Comment by jleni** [comment]
The restriction is due to bech32 definition in BIP173 and it is not purely a representation restriction.

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32
