### ISSUE TITLE
unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]  #pragma GCC diagnostic ignored "-Wstringop-overflow"

### ISSUE THREAD

**Issue by ying2025** [cosmos/ledger-cosmos-go#9]
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=0.0.0-14-gce9f584 -X github.com/cosmos/cosmos-sdk/version.Commit=ce9f584b36912ff9947f25e309f4b269785b0304 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiacli
# github.com/zondax/hid
In file included from E:\goSpace\pkg\mod\github.com\zondax\hid@v0.9.0\hid_enabled.go:40:0:
E:\goSpace\pkg\mod\github.com\zondax\hid@v0.9.0/hidapi/windows/hid.c: In function 'hid_enumerate':
E:\goSpace\pkg\mod\github.com\zondax\hid@v0.9.0/hidapi/windows/hid.c:431:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wstringop-overflow"

When I build it on window, it occur above problems.

**Comment by jleni** [comment]
This seems obsolete. Closing.
